apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: moodle-cron-rolebinding
  namespace: moodle
subjects:
- kind: ServiceAccount
  name: moodle-cron
  namespace: moodle
roleRef:
  kind: Role
  name: moodle-cron-role
  apiGroup: rbac.authorization.k8s.io