apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: moodle
  name: moodle-cron-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]