---

- name: Copy k3s
  copy:
    src: /home/av/k3s/k3s
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755

- name: make image dir
  file:
    path: /var/lib/rancher/k3s/agent/images
    state: directory
    force: no

- name: Copy k3s images
  copy:
    src: /home/av/k3s/k3s-airgap-images-amd64.tar
    dest: /var/lib/rancher/k3s/agent/images
    force: no
    owner: root
    group: root
    mode: 0755