apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: postgres-job
        image: bitnami/postgresql:15.2.0
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - while ! pg_isready -U postgres -h postgresql; do sleep 1; done; echo "CREATE DATABASE gitea;" | psql --file=- -d "host=postgresql user=postgres connect_timeout=3 sslmode=disable"
        env:
          - name: PGPASSWORD
            value: $POSTGRES_PASS
      restartPolicy: Never