alloy-api:
  # Docker image release version
  image:
    tag: '3.4.0'
  command: ["bash", "-c", "update-ca-certificates && dotnet Alloy.Api.dll"]

  # Ingress configuration example for NGINX
  # TLS and Host URLs need configured
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: 'true'
    hosts:
      - host: $DOMAIN
        paths:
          - path: /alloy/(api|swagger/hubs)
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
          - $DOMAIN

  # If this deployment needs to trust non-public certificates,
  # create a configMap with the needed certifcates and specify
  # the configMap name here
  certificateMap: 'appliance-root-ca'

  # Config app settings with environment vars.
  # Those most likely needing values are listed. For others,
  # see https://github.com/cmu-sei/crucible/blob/master/alloy.api/Alloy.Api/appsettings.json
  env:
    # Proxy Settings
    # http_proxy: proxy.example.com:9000
    # https_proxy: proxy.example.com:9000
    # HTTP_PROXY: proxy.example.com:9000
    # HTTPS_PROXY: proxy.example.com:9000
    # NO_PROXY: .local
    # no_proxy: .local
    
    ## If hosting in virtual directory, specify path base
    PathBase: "/alloy"

    Logging__LogLevel__Default: "$CRUCIBLE_LOG_LEVEL"
    Logging__LogLevel__System: "$CRUCIBLE_LOG_LEVEL"
    Logging__LogLevel__Microsoft: "$CRUCIBLE_LOG_LEVEL"
    Logging__Console__LogLevel__Default: "$CRUCIBLE_LOG_LEVEL"
    Logging__Console__LogLevel__System: "$CRUCIBLE_LOG_LEVEL"
    Logging__Console__LogLevel__Microsoft: "$CRUCIBLE_LOG_LEVEL"

    # CORS policy settings.
    # The first entry should be the URL to Alloy
    CorsPolicy__Origins__0: https://$DOMAIN
    CorsPolicy__AllowAnyMethod: true
    CorsPolicy__AllowAnyHeader: true

    # Connection String to database
    # database requires the 'uuid-ossp' extension installed
    ConnectionStrings__PostgreSQL: 'Server=postgresql;Port=5432;Database=alloy_api;Username=postgres;Password=$POSTGRES_PASS;'

    # OAuth2 Identity Client for Application
    Authorization__Authority: https://$DOMAIN/identity
    Authorization__AuthorizationUrl: https://$DOMAIN/identity/connect/authorize
    Authorization__TokenUrl: https://$DOMAIN/identity/connect/token
    Authorization__AuthorizationScope: 'alloy-api player-api caster-api steamfitter-api vm-api'
    Authorization__ClientId: alloy-api-dev
    Authorization__ClientName: 'Alloy API'

    # OAuth2 Identity Client /w Password
    ResourceOwnerAuthorization__Authority: https://$DOMAIN/identity
    ResourceOwnerAuthorization__ClientId: alloy-api
    ResourceOwnerAuthorization__UserName: crucible-admin@$DOMAIN
    ResourceOwnerAuthorization__Password: $GLOBAL_ADMIN_PASS
    ResourceOwnerAuthorization__Scope: 'alloy-api player-api caster-api steamfitter-api vm-api'

    # Crucible Application URLs
    ClientSettings__urls__playerApi: https://$DOMAIN/player/api
    ClientSettings__urls__casterApi: https://$DOMAIN/caster/api
    ClientSettings__urls__steamfitterApi: https://$DOMAIN/steamfitter/api

alloy-ui:
  # Docker image release version
  image:
    tag: '3.2.5'

  # Ingress configuration example for NGINX
  # TLS and Host URLs need configured
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: $DOMAIN
        paths:
          - path: "/alloy(/|$)(.*)"
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
          - $DOMAIN

  env: 
    ## basehref is path to the app
    APP_BASEHREF: "/alloy"

  # Config app settings with a JSON file.
  # These values correspond to an OpenID connect client and
  # some basic configuration
  # NOTE:  PlayerUIAddress is the URL to the Crucible - Player application
  settings: |-
    {
      "ApiUrl": "https://$DOMAIN/alloy",
      "OIDCSettings": {
        "authority": "https://$DOMAIN/identity/",
        "client_id": "alloy-ui",
        "redirect_uri": "https://$DOMAIN/alloy/auth-callback",
        "post_logout_redirect_uri": "https://$DOMAIN/alloy",
        "response_type": "code",
        "scope": "openid profile alloy-api player-api caster-api steamfitter-api vm-api",
        "automaticSilentRenew": true,
        "silent_redirect_uri": "https://$DOMAIN/alloy/auth-callback-silent"
      },
      "AppTitle": "Alloy",
      "AppTopBarText": "Alloy",
      "AppTopBarHexColor": "#719F94",
      "AppTopBarHexTextColor": "#FFFFFF",
      "PlayerUIAddress": "https://$DOMAIN/player",
      "PollingIntervalMS": "3500",
      "UseLocalAuthStorage": true
    }

