steamfitter-api:

  # Docker image release version
  image:
    tag: "3.7.1"
  
  # Ingress configuration example for NGINX
  # TLS and Host URLs need configured
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: $DOMAIN
        paths:
          - path: /steamfitter/(api|swagger|hubs)
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
         - $DOMAIN

  # If this deployment needs to trust non-public certificates,
  # create a configMap with the needed certifcates and specify
  # the configMap name here
  certificateMap: "appliance-root-ca"

  # Config app settings with environment vars.
  # Those most likely needing values are listed. For others,
  # see https://github.com/cmu-sei/crucible/blob/master/steamfitter.api/Steamfitter.Api/appsettings.json
  env:
    # Proxy Settings
    # https_proxy: proxy.example.com:9000
    # http_proxy: proxy.example.com:9000
    # HTTP_PROXY: proxy.example.com:9000
    # HTTPS_PROXY: proxy.example.com:9000
    # NO_PROXY: .local
    # no_proxy: .local

    ## If hosting in virtual directory, specify path base
    PathBase: "/steamfitter"

    Logging__LogLevel__Default: "$CRUCIBLE_LOG_LEVEL"
    Logging__LogLevel__System: "$CRUCIBLE_LOG_LEVEL"
    Logging__LogLevel__Microsoft: "$CRUCIBLE_LOG_LEVEL"
    Logging__Console__LogLevel__Default: "$CRUCIBLE_LOG_LEVEL"
    Logging__Console__LogLevel__System: "$CRUCIBLE_LOG_LEVEL"
    Logging__Console__LogLevel__Microsoft: "$CRUCIBLE_LOG_LEVEL"

    # Connection String to database
    # database requires the 'uuid-ossp' extension installed
    ConnectionStrings__PostgreSQL: "Server=postgresql;Port=5432;Database=steamfitter_api;Username=postgres;Password=$POSTGRES_PASS;"

    # CORS policy settings.
    # The first entry should be the URL to Steamfitter
    CorsPolicy__Origins__0: https://$DOMAIN

    # OAuth2 Identity Client for Application
    Authorization__Authority: https://$DOMAIN/identity
    Authorization__AuthorizationUrl: https://$DOMAIN/identity/connect/authorize
    Authorization__TokenUrl: https://$DOMAIN/identity/connect/token
    Authorization__AuthorizationScope: "player-api steamfitter-api vm-api"
    Authorization__ClientId: steamfitter-api-dev
    Authorization__ClientName: "Steamfitter API"

    # OAuth2 Identity Client /w Password
    ResourceOwnerAuthorization__Authority: https://$DOMAIN/identity
    ResourceOwnerAuthorization__ClientId: steamfitter-api
    ResourceOwnerAuthorization__UserName: crucible-admin@$DOMAIN
    ResourceOwnerAuthorization__Password: $CRUCIBLE_ADMIN_PASS
    ResourceOwnerAuthorization__Scope: "vm-api"

    # Crucible URLs
    ClientSettings__urls__playerApi: https://$DOMAIN/player/api
    ClientSettings__urls__vmApi: https://$DOMAIN/vm/api

    # Stackstorm Configuration
    # TODO - Document Stackstorm dependencies
    VmTaskProcessing__ApiType: st2
    VmTaskProcessing__ApiUsername: "administrator"
    VmTaskProcessing__ApiPassword: "$GLOBAL_ADMIN_PASS"
    VmTaskProcessing__ApiBaseUrl: "https://$DOMAIN/stackstorm"
    VmTaskProcessing__ApiParameters__clusters: ""

    # Basic seed data to jumpstart deployement
    # TODO - Document Seed data
    SeedData__Users__0__id: "dee684c5-2eaf-401a-915b-d3d4320fe5d5"
    SeedData__Users__0__name:  "administrator@$DOMAIN"
    SeedData__Users__1__id: "32c11441-7eec-47eb-a915-607c4f2529f4"
    SeedData__Users__1__name:  "crucible-admin@$DOMAIN"
    

    SeedData__UserPermissions__0__UserId: "dee684c5-2eaf-401a-915b-d3d4320fe5d5"
    SeedData__UserPermissions__0__PermissionId: "00000000-0000-0000-0000-000000000001"
    SeedData__UserPermissions__1__UserId: "32c11441-7eec-47eb-a915-607c4f2529f4"
    SeedData__UserPermissions__1__PermissionId: "00000000-0000-0000-0000-000000000001"

steamfitter-ui:

  # Docker image release version
  image:
    tag: "3.7.2"

  # Ingress configuration example for NGINX
  # TLS and Host URLs need configured
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-read-timeout: '86400'
      nginx.ingress.kubernetes.io/proxy-send-timeout: '86400'
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: $DOMAIN
        paths:
          - path: "/steamfitter(/|$)(.*)"
            pathType: Prefix
    tls:
      - secretName: appliance-cert
        hosts:
         - $DOMAIN

  env: 
    ## basehref is path to the app
    APP_BASEHREF: "/steamfitter"

  # Config app settings with a JSON file.
  # These values correspond to an OpenID connect client
  settings: |-
    {
      "ApiUrl": "https://$DOMAIN/steamfitter",
      "VmApiUrl": "https://$DOMAIN/vm",
      "ApiPlayerUrl": "https://$DOMAIN/player",
      "OIDCSettings": {
          "authority": "https://$DOMAIN/identity",
          "client_id": "steamfitter-ui",
          "redirect_uri": "https://$DOMAIN/steamfitter/auth-callback",
          "post_logout_redirect_uri": "https://$DOMAIN/steamfitter",
          "response_type": "code",
          "scope": "openid profile steamfitter-api vm-api player-api",
          "automaticSilentRenew": true,
          "silent_redirect_uri": "https://$DOMAIN/steamfitter/auth-callback-silent"
      },
      "AppTitle": "Steamfitter",
      "AppTopBarHexColor": "#EF3A47",
      "AppTopBarHexTextColor": "#FFFFFF",
      "UseLocalAuthStorage": true
    }
